### ISSUE TITLE
This should be fixed in 2019.2.9f1

### ISSUE THREAD

**Issue by mikerz** [keijiro/MultiDisplayTest#1]

**Comment by keijiro** [comment]
Could you provide any information?

**Comment by mikerz** [comment]
Sure just letting you know the bug this exposes is fixed as of the listed version. Previously, secondary cameras would not render correctly if the screen resolution was different from the primary display. Now a 4k and HD monitor will play nicely together with MultiDisplay

**Comment by keijiro** [comment]
Thanks but I knew it works correctly when I created this repository. I verified it using this project.
